### ISSUE TITLE
clear button style with multiple is absent

### ISSUE THREAD

**Issue by Alxdhere** [select2/select2-bootstrap-theme#11]
There are not css for select2-selection__clear with multiple=true (select2-selection--multiple). Clear button render after inline input, but not at right side of select2 control.
![Screenshot](http://alxd.it-dept.ru/images/select2-theme-bug-01.png)

**Comment by fk** [comment]
Not closed yet because of this issue:

![select2-clear](https://cloud.githubusercontent.com/assets/21834/8336663/5cd6bd80-1aa6-11e5-8c99-fc15a8640bbd.gif)

**Comment by fk** [comment]
Closing as this as
- the original issue has been fixed
- the bug that came up while solving the original issue (that is unrelated to the latter and shown in the GIF in my previous comment ("Select2 multi append Radiobutton")) is tracked in https://github.com/select2/select2/issues/4367
- the bug is easily avoided by _not_ providing an empty `<option></option>` for multi Select2 widgets (contrary to single Select2, where the placeholder feature _requires_ an empty `<option></option>`)
- http://codepen.io/fk/pen/bepgOw provides an isolated, working example
- the select2-bootstrap-theme demo will be updated to remove the conflicting `<option></option>` for the "Select2 multi append Radiobutton" Select2.
