### ISSUE TITLE
Component doesen't resizes

### ISSUE THREAD

**Issue by gasparuhov** [select2/select2-bootstrap-theme#15]
I am not sure if I am doing something wrong or it is an issue. When I resize the browser window or inspect the page for mobile devices the component is not shrinking it stays the same size.
![untitled](https://cloud.githubusercontent.com/assets/5780569/8079597/67a17126-0f6e-11e5-9e43-3c48ecad550c.png)

**Comment by cyberbit** [comment]
@gasparuhov I've found that having a combination of the `form-control` class and an inline style of `width: 100%` works for almost every case in Bootstrap.

I guess a follow up would be if the boxes are the right size when you reload the page while inspecting the mobile view. If they are, then the above solution should solve that.

The reason for the inline style is because it seems like Select2 doesn't copy percentage widths properly when defined in classes, but explicitly providing one will force it to copy that rather than an equivalent pixel width.

**Comment by fk** [comment]
@gasparuhov Do the [demo pages](https://select2.github.io/select2-bootstrap-theme/4.0.0.html) work for you? We're passing [`width: null`](https://github.com/select2/select2-bootstrap-theme/blob/master/docs/_layouts/default.html#L530) to prevent Select2 from copying the width of the original `select` element to the `.select2-container`.

If you want me to take a look please provide a JSFiddle, CodePen or similar.

**Comment by gasparuhov** [comment]
@cyberbit Thank you, refreshing the page works fine for me.
