### ISSUE TITLE
Wrong path to bootstrap

### ISSUE THREAD

**Issue by Invis1ble** [select2/select2-bootstrap-theme#16]
Hi. First of all, thanks for the great work.
Seems like there is a wrong path to bootstrap `*.less` files in [build.less](https://github.com/select2/select2-bootstrap-theme/blob/master/src/build.less)

**Comment by fk** [comment]
Hi @Invis1ble and thanks for your nice words!

The paths in `src/build.less` should be working fine, however …
- the Less source (`src/select2-bootstrap.less`) was not in line with the Sass version
- the patch file in `tests/support/less.patch` required to run the tests (`grunt nodeunit` or `npm test`) was empty
- the path to the Less build source file in `tests/less_test.js` was falsely set to `src/select2-bootstrap.less` instead of `src/build.less`

All aforementioned issues should be fixed with 3e86f34f6c94302cd8b4d6c3d751c5fb70fe61f6.
Even without those fixes, you should have been able to run e. g. `lessc --verbose src/build.less dist/select2-bootstrap.less.css` from the repository's root to compile the Less source.

How have you been trying to compile the Less source?
What errors did you run into?

**Comment by Invis1ble** [comment]
Hi @fk 
Now I see, you have bootstrap as dependency and it installs in the root of repo.
I have bootstrap as dependency of my project too and it installs in `../../bootstrap` relatively to `build.less`.
I install `select2-bootstrap-theme` via `bower install` so there is no `bower_components/select2-bootstrap-theme/bower_components/bootstrap`, trying to compile via Grunt having

``` less
@import "../../../../../../bower_components/select2-bootstrap-theme/src/build.less";
```

in my less-file and I get error FileError:

> Running "less:backofficeCommonStyles" (less) task
> &gt;&gt; FileError: '../bower_components/bootstrap/less/variables.less' wasn't found. Tried - bower_components/select2-bootstrap-theme/bower_components/bootstrap/less/variables.less,src/Application/BackofficeBundle/Resources/bower_components/bootstrap/less/variables.less,../bower_components/bootstrap/less/variables.less in bower_components/select2-bootstrap-theme/src/build.less on line 1, column 1:
> &gt;&gt; 1 @import "../bower_components/bootstrap/less/variables";
> &gt;&gt; 2 @import "../bower_components/bootstrap/less/mixins";
> Warning: Error compiling src/Application/BackofficeBundle/Resources/less/common.less Use --force to continue.
> 
> Aborted due to warnings.

**Comment by fk** [comment]
Thanks for reporting back @Invis1ble; a heads up regarding building based on your own version of Bootstrap will go into the readme as soon as I find the time (or someone submits a pull request).

To fix your issue, I would advise to create your own version of `build.less` – if I understood you, it should look something like this:

```
@import "../../../../../../bower_components/bootstrap/less/variables";
@import "../../../../../../bower_components/bootstrap/less/mixins";
@import "../../../../../../bower_components/select2-bootstrap-theme/src/select2-bootstrap.less";
```

Let me know if this works or if I missed something!

**Comment by Invis1ble** [comment]
Yes, this snippet works for me. In a final version I removed importing of `variables` and `mixins` because its already imported before `select2`. So my code imports only `select2-bootstrap.less`.

Thanks for help.

**Comment by fk** [comment]
You're welcome!
