### ISSUE TITLE
Not for production?

### ISSUE THREAD

**Issue by alvarotrigo** [select2/select2-bootstrap-theme#22]
> Note: Work in progress – depending on your use case, select2-bootstrap-theme might not be production-ready yet!

Could you specify why in the documentation? And for which cases is it not ready? 

Those are the things I would expect to see in the **Compatibility** section of the documentation before deciding to choose it or not.

**Comment by fk** [comment]
Hi @alvarotrigo – thanks for raising this very valid question!
Please accept my apologies for addressing it so "late" (which is an understatement).

At the time this note was added to the README, select2-bootstrap-theme was nothing more than a rushed, first shot at converting its legacy project, https://github.com/t0m/select2-bootstrap-css/tree/bootstrap3, which targeted Select2 v3, to work with Select2 v4 and its new theming capabilities. It was only tested in latest Chrome and had a bunch of issues in "multi-select" mode – the latter being the main thing that the "might not be production-ready yet" line was referencing.

However, the project has matured quite a bit since its first release and the lines you referenced from the README make things sound a lot worse than they are by now – so I finally removed them, and also took your advice and added the "Compatibility" section to the README.

**Comment by alvarotrigo** [comment]
@fk nice to hear!
